/** @noformat */
// This file is automatically generated by scripts/build-account-sync-cloud-function.mjs. Do not edit directly.

"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  try {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  } catch (e) {
    throw mod = 0, e;
  }
};

// cloudfunctions/accountSync/lib/account-key.js
var require_account_key = __commonJS({
  "cloudfunctions/accountSync/lib/account-key.js"(exports2, module2) {
    "use strict";
    var crypto = require("node:crypto");
    var createAccountKey = (appId, openId) => crypto.createHash("sha256").update(`${appId}:${openId}`).digest("hex");
    module2.exports = { createAccountKey };
  }
});

// cloudfunctions/accountSync/lib/cloud-store.js
var require_cloud_store = __commonJS({
  "cloudfunctions/accountSync/lib/cloud-store.js"(exports2, module2) {
    "use strict";
    var CloudStore = class _CloudStore {
      constructor(database, serverDate = () => database.serverDate()) {
        this.database = database;
        this.serverDate = serverDate;
      }
      async transaction(work) {
        const result = await this.database.runTransaction(
          async (transaction) => work(new _CloudStore(transaction, this.serverDate))
        );
        return result && typeof result === "object" && Object.hasOwn(result, "result") ? result.result : result;
      }
      async getAccount(id) {
        const result = await this.database.collection("user_accounts").doc(id).get();
        return _CloudStore.withoutDocumentId(result.data);
      }
      async getProgress(id) {
        const result = await this.database.collection("user_progress").doc(id).get();
        return _CloudStore.withoutDocumentId(result.data);
      }
      static withoutDocumentId(data) {
        if (!data) {
          return null;
        }
        const value = { ...data };
        delete value._id;
        return value;
      }
      async createAccount(id, value) {
        const now = this.serverDate();
        await this.database.collection("user_accounts").doc(id).set({
          data: { ...value, created_at: now, updated_at: now }
        });
      }
      async createProgress(id, value) {
        const now = this.serverDate();
        await this.database.collection("user_progress").doc(id).set({
          data: { ...value, created_at: now, updated_at: now }
        });
      }
      async saveAccount(id, value) {
        await this.database.collection("user_accounts").doc(id).update({
          data: { ..._CloudStore.withoutDocumentId(value), updated_at: this.serverDate() }
        });
      }
      async saveProgress(id, value) {
        await this.database.collection("user_progress").doc(id).update({
          data: { ..._CloudStore.withoutDocumentId(value), updated_at: this.serverDate() }
        });
      }
      async getRecord(id) {
        const result = await this.database.collection("user_practice_records").doc(id).get();
        return _CloudStore.withoutDocumentId(result.data);
      }
      async createRecord(id, value) {
        await this.database.collection("user_practice_records").doc(id).set({ data: { ...value, submitted_at: this.serverDate() } });
      }
      async listRecordIdsForAccount(accountKey) {
        const result = await this.database.collection("user_practice_records").where({ account_key: accountKey }).orderBy("submitted_at", "asc").limit(50).get();
        return (result.data || []).map((record) => record._id);
      }
      async removeRecords(ids) {
        await Promise.all(
          ids.map((id) => this.database.collection("user_practice_records").doc(id).remove())
        );
      }
      async removeProgress(id) {
        await this.database.collection("user_progress").doc(id).remove();
      }
      async removeAccount(id) {
        await this.database.collection("user_accounts").doc(id).remove();
      }
    };
    module2.exports = { CloudStore };
  }
});

// cloudfunctions/accountSync/lib/errors.js
var require_errors = __commonJS({
  "cloudfunctions/accountSync/lib/errors.js"(exports2, module2) {
    "use strict";
    var AccountSyncError = class extends Error {
      constructor(code) {
        super(code);
        this.code = code;
      }
    };
    var toErrorResponse = (error) => ({
      ok: false,
      error: {
        code: error instanceof AccountSyncError ? error.code : "ACCOUNT_SYNC_UNAVAILABLE"
      }
    });
    module2.exports = { AccountSyncError, toErrorResponse };
  }
});

// cloudfunctions/accountSync/lib/validation.js
var require_validation = __commonJS({
  "cloudfunctions/accountSync/lib/validation.js"(exports2, module2) {
    "use strict";
    var { AccountSyncError } = require_errors();
    var ACTION_FIELDS = {
      bootstrap: ["action", "schemaVersion"],
      updateProfile: ["action", "schemaVersion", "expectedRevision", "nickname", "avatarUrl"],
      updatePreferences: [
        "action",
        "schemaVersion",
        "expectedRevision",
        "selectedCertificateKey",
        "dailyGoal",
        "answerTheme",
        "answerRevealMode"
      ],
      saveActiveSession: ["action", "schemaVersion", "expectedRevision", "session"],
      setFavorite: ["action", "schemaVersion", "expectedRevision", "questionId", "favorite"],
      markMastered: ["action", "schemaVersion", "expectedRevision", "questionId", "mastered"],
      recordPractice: ["action", "schemaVersion", "expectedRevision", "sessionId", "mode", "answers"],
      clearLearningData: ["action", "schemaVersion"],
      deleteAccount: ["action", "schemaVersion"]
    };
    var PLATFORM_EVENT_FIELDS = /* @__PURE__ */ new Set(["tcbContext", "userInfo"]);
    var AVATAR_PATHS = /* @__PURE__ */ new Set([
      "/assets/avatars/granary.svg",
      "/assets/avatars/wheat.svg",
      "/assets/avatars/field.svg",
      "/assets/avatars/book.svg"
    ]);
    var isRecord = (value) => typeof value === "object" && value !== null && !Array.isArray(value);
    var isKnownAction = (action) => typeof action === "string" && Object.prototype.hasOwnProperty.call(ACTION_FIELDS, action);
    var invalid = () => {
      throw new AccountSyncError("INVALID_REQUEST");
    };
    var isRevision = (value) => Number.isInteger(value) && value >= 0;
    var isQuestionId = (value) => typeof value === "string" && value.length <= 64 && /^(?:Q\d+|[A-Z]{2,}(?:-[A-Z0-9]+)+)$/.test(value);
    var isDate = (value) => {
      if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
      const date = /* @__PURE__ */ new Date(`${value}T00:00:00.000Z`);
      return !Number.isNaN(date.valueOf()) && date.toISOString().slice(0, 10) === value;
    };
    var validateEvent = (event) => {
      if (!isRecord(event) || typeof event.action !== "string") invalid();
      if (event.schemaVersion !== 1) throw new AccountSyncError("SCHEMA_INCOMPATIBLE");
      const allowed = ACTION_FIELDS[event.action];
      if (!allowed || Object.keys(event).some((key) => !allowed.includes(key) && !PLATFORM_EVENT_FIELDS.has(key)))
        invalid();
      if (!["bootstrap", "clearLearningData", "deleteAccount"].includes(event.action) && !isRevision(event.expectedRevision))
        invalid();
      return event;
    };
    var validateProfile = (event) => {
      if (typeof event.nickname !== "string" || !event.nickname.trim() || Array.from(event.nickname).length > 12 || typeof event.avatarUrl !== "string" || event.avatarUrl !== "" && !AVATAR_PATHS.has(event.avatarUrl)) {
        invalid();
      }
    };
    var validatePreferences = (event) => {
      if (typeof event.selectedCertificateKey !== "string" || !/^(4-02-06-01|4-08-05-01):[1-5]$/.test(event.selectedCertificateKey) || !Number.isInteger(event.dailyGoal) || event.dailyGoal < 1 || event.dailyGoal > 100 || !["light", "night"].includes(event.answerTheme) || !["immediate", "deferred"].includes(event.answerRevealMode)) {
        invalid();
      }
    };
    var validateQuestionState = (event, stateField) => {
      if (!isQuestionId(event.questionId) || typeof event[stateField] !== "boolean") invalid();
    };
    var validateSession = (event) => {
      if (event.session === null) return;
      const session = event.session;
      const allowed = /* @__PURE__ */ new Set([
        "id",
        "mode",
        "questionIds",
        "currentIndex",
        "answers",
        "status",
        "startedAt",
        "updatedAt",
        "submittedAt",
        "progressRecorded",
        "answerRevealMode"
      ]);
      if (!isRecord(session) || Object.keys(session).some((key) => !allowed.has(key)) || typeof session.id !== "string" || !session.id.trim() || !["chapter", "sequential", "random", "mock", "wrong", "favorite"].includes(session.mode) || !Array.isArray(session.questionIds) || session.questionIds.length === 0 || session.questionIds.length > 100 || !session.questionIds.every(isQuestionId) || new Set(session.questionIds).size !== session.questionIds.length || !Number.isInteger(session.currentIndex) || session.currentIndex < 0 || session.currentIndex >= session.questionIds.length || !isRecord(session.answers) || !Object.entries(session.answers).every(
        ([questionId, answers]) => session.questionIds.includes(questionId) && Array.isArray(answers) && answers.length > 0 && answers.length <= 10 && answers.every(
          (answer) => typeof answer === "string" && answer.length > 0 && answer.length <= 10
        )
      ) || !["active", "submitted"].includes(session.status) || !Number.isFinite(session.startedAt) || session.startedAt < 0 || !Number.isFinite(session.updatedAt) || session.updatedAt < 0 || session.submittedAt !== void 0 && (!Number.isFinite(session.submittedAt) || session.submittedAt < 0) || session.progressRecorded !== void 0 && typeof session.progressRecorded !== "boolean" || session.status === "submitted" && session.submittedAt === void 0 || !["immediate", "deferred"].includes(session.answerRevealMode)) {
        invalid();
      }
    };
    var validatePractice = (event) => {
      const answerFields = /* @__PURE__ */ new Set(["questionId", "correct", "durationMs", "at"]);
      if (!["chapter", "sequential", "random", "mock", "wrong", "favorite"].includes(event.mode) || typeof event.sessionId !== "string" || !event.sessionId.trim() || event.sessionId.length > 128 || !Array.isArray(event.answers) || event.answers.length === 0 || event.answers.length > 100 || !event.answers.every(
        (answer) => isRecord(answer) && Object.keys(answer).length === answerFields.size && Object.keys(answer).every((key) => answerFields.has(key)) && isQuestionId(answer.questionId) && typeof answer.correct === "boolean" && Number.isInteger(answer.durationMs) && answer.durationMs >= 0 && answer.durationMs <= 864e5 && isDate(answer.at)
      ))
        invalid();
    };
    module2.exports = {
      isKnownAction,
      validateEvent,
      validateProfile,
      validatePreferences,
      validateQuestionState,
      validateSession,
      validatePractice
    };
  }
});

// cloudfunctions/accountSync/lib/handler.js
var require_handler = __commonJS({
  "cloudfunctions/accountSync/lib/handler.js"(exports2, module2) {
    "use strict";
    var { AccountSyncError, toErrorResponse } = require_errors();
    var { Buffer: Buffer2 } = require("node:buffer");
    var { createHash } = require("node:crypto");
    var {
      validateEvent,
      validateProfile,
      validatePreferences,
      validateQuestionState,
      validateSession,
      validatePractice
    } = require_validation();
    var MAX_SNAPSHOT_RESPONSE_BYTES = 900 * 1024;
    var emptyAccount = () => ({
      schema_version: 1,
      status: "active",
      learning_clear_state: "idle",
      revision: 0,
      nickname: "\u4ED3\u5EEA\u5C0F\u9EA6",
      avatar_url: "",
      selected_certificate_key: "4-02-06-01:5",
      daily_goal: 20,
      answer_theme: "light",
      answer_reveal_mode: "immediate"
    });
    var emptyProgress = () => ({
      schema_version: 1,
      revision: 0,
      summary: { answered: 0, correct: 0, duration_ms: 0, first_answered_at: null },
      question_totals: {},
      wrong_questions: {},
      favorites: {},
      daily_totals: {},
      recent_question_ids: [],
      active_session: null
    });
    var createPracticeRecordId = (accountKey, sessionId) => `record_${createHash("sha256").update(`${accountKey}:${sessionId}`).digest("hex")}`;
    var fromStoredSession = (session) => session && {
      id: session.id,
      mode: session.mode,
      questionIds: session.question_ids,
      currentIndex: session.current_index,
      answers: session.answers,
      status: session.status,
      startedAt: session.started_at,
      updatedAt: session.updated_at,
      ...session.submitted_at === void 0 ? {} : { submittedAt: session.submitted_at },
      ...session.progress_recorded === void 0 ? {} : { progressRecorded: session.progress_recorded },
      answerRevealMode: session.answer_reveal_mode
    };
    var toStoredSession = (session) => session && {
      id: session.id,
      mode: session.mode,
      question_ids: session.questionIds,
      current_index: session.currentIndex,
      answers: session.answers,
      status: session.status,
      started_at: session.startedAt,
      updated_at: session.updatedAt,
      ...session.submittedAt === void 0 ? {} : { submitted_at: session.submittedAt },
      ...session.progressRecorded === void 0 ? {} : { progress_recorded: session.progressRecorded },
      answer_reveal_mode: session.answerRevealMode
    };
    var fromStoredWrongQuestions = (records) => Object.fromEntries(
      Object.entries(records).map(([questionId, record]) => [
        questionId,
        {
          questionId: record.question_id,
          errorCount: record.error_count,
          firstWrongAt: record.first_wrong_at,
          lastWrongAt: record.last_wrong_at,
          mastered: record.mastered,
          lastRetryCorrect: record.last_retry_correct
        }
      ])
    );
    var camelCaseTotals = (totals) => Object.fromEntries(
      Object.entries(totals).map(([questionId, total]) => [
        questionId,
        { attempts: total.attempts, correctAttempts: total.correct_attempts }
      ])
    );
    var camelCaseDailyTotals = (totals) => Object.fromEntries(
      Object.entries(totals).map(([date, total]) => [
        date,
        { answered: total.answered, correct: total.correct, durationMs: total.duration_ms }
      ])
    );
    var toSnapshot = (account, progress, now) => ({
      schemaVersion: 1,
      profileRevision: account.revision,
      progressRevision: progress.revision,
      syncedAt: now(),
      profile: {
        nickname: account.nickname,
        avatarUrl: account.avatar_url,
        selectedCertificateKey: account.selected_certificate_key,
        dailyGoal: account.daily_goal,
        answerTheme: account.answer_theme,
        answerRevealMode: account.answer_reveal_mode
      },
      progress: {
        schemaVersion: 4,
        summary: {
          answered: progress.summary.answered,
          correct: progress.summary.correct,
          durationMs: progress.summary.duration_ms,
          firstAnsweredAt: progress.summary.first_answered_at
        },
        questionTotals: camelCaseTotals(progress.question_totals),
        wrongQuestions: fromStoredWrongQuestions(progress.wrong_questions),
        favorites: progress.favorites,
        session: fromStoredSession(progress.active_session),
        dailyTotals: camelCaseDailyTotals(progress.daily_totals),
        recentQuestionIds: progress.recent_question_ids,
        recordedSessionIds: [],
        preferences: {
          nickname: account.nickname,
          avatarUrl: account.avatar_url,
          selectedCertificateKey: account.selected_certificate_key,
          dailyGoal: account.daily_goal,
          answerTheme: account.answer_theme,
          answerRevealMode: account.answer_reveal_mode
        }
      }
    });
    var snapshotResponse = (account, progress, now) => {
      const response = { ok: true, data: toSnapshot(account, progress, now) };
      if (Buffer2.byteLength(JSON.stringify(response), "utf8") > MAX_SNAPSHOT_RESPONSE_BYTES) {
        throw new AccountSyncError("ACCOUNT_SYNC_UNAVAILABLE");
      }
      return response;
    };
    var createHandler = ({ store, hash, now = () => (/* @__PURE__ */ new Date()).toISOString(), inTransaction = false }) => async (event, context) => {
      if (!inTransaction && typeof store.transaction === "function") {
        return store.transaction(
          (transactionStore) => createHandler({ store: transactionStore, hash, now, inTransaction: true })(
            event,
            context
          )
        ).catch(toErrorResponse);
      }
      try {
        const request = validateEvent(event);
        if (!context || !context.APPID || !context.OPENID || typeof context.APPID !== "string" || typeof context.OPENID !== "string") {
          throw new AccountSyncError("INVALID_REQUEST");
        }
        const key = hash(context.APPID, context.OPENID);
        const accountId = `account_${key}`;
        const progressId = `progress_${key}`;
        let account = await store.getAccount(accountId);
        let progress = await store.getProgress(progressId);
        if (request.action === "bootstrap") {
          if (!account) {
            account = emptyAccount();
            await store.createAccount(accountId, account);
          }
          if (!progress) {
            progress = emptyProgress();
            await store.createProgress(progressId, progress);
          }
          return snapshotResponse(account, progress, now);
        }
        if (request.action === "deleteAccount") {
          if (!account) return { ok: true, data: { schemaVersion: 1, done: true, stage: "done" } };
          if (account.status !== "deleting") {
            await store.saveAccount(accountId, { ...account, status: "deleting" });
            return { ok: true, data: { schemaVersion: 1, done: false, stage: "records" } };
          }
          const recordIds = await store.listRecordIdsForAccount(key);
          if (recordIds.length > 0) {
            await store.removeRecords(recordIds);
            return { ok: true, data: { schemaVersion: 1, done: false, stage: "records" } };
          }
          if (progress) await store.removeProgress(progressId);
          await store.removeAccount(accountId);
          return { ok: true, data: { schemaVersion: 1, done: true, stage: "done" } };
        }
        if (!account || !progress) throw new AccountSyncError("ACCOUNT_SYNC_UNAVAILABLE");
        if (request.action === "clearLearningData") {
          if (account.status === "deleting") throw new AccountSyncError("ACCOUNT_DELETING");
          if (account.learning_clear_state !== "clearing") {
            await store.saveAccount(accountId, { ...account, learning_clear_state: "clearing" });
            return { ok: false, error: { code: "ACCOUNT_SYNC_UNAVAILABLE" } };
          }
          const recordIds = await store.listRecordIdsForAccount(key);
          if (recordIds.length > 0) {
            await store.removeRecords(recordIds);
            if ((await store.listRecordIdsForAccount(key)).length > 0) {
              return { ok: false, error: { code: "ACCOUNT_SYNC_UNAVAILABLE" } };
            }
          }
          progress = emptyProgress();
          await store.saveProgress(progressId, progress);
          account = { ...account, learning_clear_state: "idle" };
          await store.saveAccount(accountId, account);
          return snapshotResponse(account, progress, now);
        }
        if (account.status === "deleting") throw new AccountSyncError("ACCOUNT_DELETING");
        if (account.status !== "active" || account.learning_clear_state !== "idle") {
          throw new AccountSyncError("ACCOUNT_DELETING");
        }
        if (request.action === "updateProfile") {
          validateProfile(request);
          const matches = account.nickname === request.nickname && account.avatar_url === request.avatarUrl;
          if (!matches && request.expectedRevision !== account.revision) {
            throw new AccountSyncError("REVISION_CONFLICT");
          }
          if (!matches) {
            account = {
              ...account,
              nickname: request.nickname,
              avatar_url: request.avatarUrl,
              revision: account.revision + 1
            };
            await store.saveAccount(accountId, account);
          }
        } else if (request.action === "updatePreferences") {
          validatePreferences(request);
          const matches = account.selected_certificate_key === request.selectedCertificateKey && account.daily_goal === request.dailyGoal && account.answer_theme === request.answerTheme && account.answer_reveal_mode === request.answerRevealMode;
          if (!matches && request.expectedRevision !== account.revision)
            throw new AccountSyncError("REVISION_CONFLICT");
          if (!matches) {
            account = {
              ...account,
              selected_certificate_key: request.selectedCertificateKey,
              daily_goal: request.dailyGoal,
              answer_theme: request.answerTheme,
              answer_reveal_mode: request.answerRevealMode,
              revision: account.revision + 1
            };
            await store.saveAccount(accountId, account);
          }
        } else if (request.action === "saveActiveSession") {
          validateSession(request);
          const storedSession = toStoredSession(request.session);
          const matches = JSON.stringify(progress.active_session) === JSON.stringify(storedSession);
          if (!matches && request.expectedRevision !== progress.revision)
            throw new AccountSyncError("REVISION_CONFLICT");
          if (!matches) {
            progress = {
              ...progress,
              active_session: storedSession,
              revision: progress.revision + 1
            };
            await store.saveProgress(progressId, progress);
          }
        } else if (request.action === "setFavorite") {
          validateQuestionState(request, "favorite");
          const current = Object.hasOwn(progress.favorites, request.questionId);
          if (current !== request.favorite && request.expectedRevision !== progress.revision) {
            throw new AccountSyncError("REVISION_CONFLICT");
          }
          if (current !== request.favorite) {
            const favorites = { ...progress.favorites };
            if (request.favorite) favorites[request.questionId] = Date.now();
            else delete favorites[request.questionId];
            progress = { ...progress, favorites, revision: progress.revision + 1 };
            await store.saveProgress(progressId, progress);
          }
        } else if (request.action === "markMastered") {
          validateQuestionState(request, "mastered");
          const record = progress.wrong_questions[request.questionId];
          if (!record) throw new AccountSyncError("INVALID_REQUEST");
          const matches = record.mastered === request.mastered;
          if (!matches && request.expectedRevision !== progress.revision)
            throw new AccountSyncError("REVISION_CONFLICT");
          if (!matches) {
            progress = {
              ...progress,
              wrong_questions: {
                ...progress.wrong_questions,
                [request.questionId]: {
                  ...record,
                  mastered: request.mastered,
                  last_retry_correct: request.mastered
                }
              },
              revision: progress.revision + 1
            };
            await store.saveProgress(progressId, progress);
          }
        } else if (request.action === "recordPractice") {
          validatePractice(request);
          const recordId = createPracticeRecordId(key, request.sessionId);
          if (!store.getRecord || !await store.getRecord(recordId)) {
            if (request.expectedRevision !== progress.revision)
              throw new AccountSyncError("REVISION_CONFLICT");
            const summary = { ...progress.summary };
            const questionTotals = { ...progress.question_totals };
            const dailyTotals = { ...progress.daily_totals };
            const wrongQuestions = { ...progress.wrong_questions };
            let recentQuestionIds = [...progress.recent_question_ids];
            for (const answer of request.answers) {
              summary.answered += 1;
              summary.correct += answer.correct ? 1 : 0;
              summary.duration_ms += answer.durationMs;
              const total = questionTotals[answer.questionId] || { attempts: 0, correct_attempts: 0 };
              questionTotals[answer.questionId] = {
                attempts: total.attempts + 1,
                correct_attempts: total.correct_attempts + (answer.correct ? 1 : 0)
              };
              const day = dailyTotals[answer.at] || { answered: 0, correct: 0, duration_ms: 0 };
              dailyTotals[answer.at] = {
                answered: day.answered + 1,
                correct: day.correct + (answer.correct ? 1 : 0),
                duration_ms: day.duration_ms + answer.durationMs
              };
              summary.first_answered_at = summary.first_answered_at === null || answer.at < summary.first_answered_at ? answer.at : summary.first_answered_at;
              const wrong = wrongQuestions[answer.questionId];
              if (!answer.correct) {
                wrongQuestions[answer.questionId] = wrong ? {
                  ...wrong,
                  error_count: wrong.error_count + 1,
                  last_wrong_at: answer.at,
                  mastered: false,
                  last_retry_correct: false
                } : {
                  question_id: answer.questionId,
                  error_count: 1,
                  first_wrong_at: answer.at,
                  last_wrong_at: answer.at,
                  mastered: false,
                  last_retry_correct: false
                };
              } else if (wrong) {
                wrongQuestions[answer.questionId] = { ...wrong, last_retry_correct: true };
              }
              recentQuestionIds = [
                answer.questionId,
                ...recentQuestionIds.filter((questionId) => questionId !== answer.questionId)
              ].slice(0, 100);
            }
            if (store.createRecord)
              await store.createRecord(recordId, {
                schema_version: 1,
                account_key: key,
                session_id: request.sessionId,
                mode: request.mode,
                answers: request.answers.map((answer) => ({
                  question_id: answer.questionId,
                  correct: answer.correct,
                  duration_ms: answer.durationMs,
                  answered_at: answer.at
                })),
                answered: request.answers.length,
                correct: request.answers.filter((answer) => answer.correct).length,
                duration_ms: request.answers.reduce((total, answer) => total + answer.durationMs, 0)
              });
            progress = {
              ...progress,
              summary,
              question_totals: questionTotals,
              wrong_questions: wrongQuestions,
              daily_totals: dailyTotals,
              recent_question_ids: recentQuestionIds,
              active_session: progress.active_session && progress.active_session.id === request.sessionId ? null : progress.active_session,
              revision: progress.revision + 1
            };
            await store.saveProgress(progressId, progress);
          }
        }
        return snapshotResponse(account, progress, now);
      } catch (error) {
        if (inTransaction) throw error;
        return toErrorResponse(error);
      }
    };
    module2.exports = { createHandler, emptyAccount, emptyProgress, createPracticeRecordId };
  }
});

// cloudfunctions/accountSync/src/index.js
var logger = require("node:console");
var runtime;
var getRuntime = () => {
  if (runtime) return runtime;
  logger.info("[accountSync] initializing");
  const cloud = require("wx-server-sdk");
  const { createAccountKey } = require_account_key();
  const { CloudStore } = require_cloud_store();
  const { createHandler } = require_handler();
  const { isKnownAction } = require_validation();
  cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
  runtime = {
    cloud,
    handler: createHandler({
      store: new CloudStore(cloud.database({ throwOnNotFound: false })),
      hash: createAccountKey
    }),
    isKnownAction
  };
  logger.info("[accountSync] initialized");
  return runtime;
};
exports.main = async (event) => {
  logger.info("[accountSync] invoked");
  try {
    const initialized = getRuntime();
    const context = initialized.cloud.getWXContext();
    const requestedAction = event && typeof event.action === "string" ? event.action : void 0;
    logger.info("[accountSync] request", {
      action: initialized.isKnownAction(requestedAction) ? requestedAction : "invalid"
    });
    return await initialized.handler(event, context);
  } catch (error) {
    logger.error("[accountSync] unhandled", {
      name: error instanceof Error ? error.name : "UnknownError",
      code: error && typeof error === "object" && "code" in error ? String(error.code) : void 0
    });
    return { ok: false, error: { code: "ACCOUNT_SYNC_UNAVAILABLE" } };
  }
};
