import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const entrySource = readFileSync(
  new URL('../cloudfunctions/accountSync/index.js', import.meta.url),
  'utf8',
);
const sourceEntry = readFileSync(
  new URL('../cloudfunctions/accountSync/src/index.js', import.meta.url),
  'utf8',
);

describe('accountSync cloud function entry', () => {
  it('is a generated self-contained CommonJS bundle that leaves only the cloud SDK external', () => {
    expect(entrySource).toContain(
      '// This file is automatically generated by scripts/build-account-sync-cloud-function.mjs.',
    );
    expect(entrySource).toMatch(/require\(['"]wx-server-sdk['"]\)/);
    expect(entrySource).not.toMatch(/require\(['"]\.{1,2}\/lib\//);
  });

  it('configures missing document reads on the CloudBase database adapter', () => {
    expect(entrySource).toContain(
      'store: new CloudStore(cloud.database({ throwOnNotFound: false }))',
    );
  });

  it('sanitizes entry logs before emitting request or error details', () => {
    const logStatements = [...sourceEntry.matchAll(/logger\.[A-Za-z_$][\w$]*\([\s\S]*?\);/g)].map(
      (match) => match[0],
    );

    expect(logStatements).toEqual([
      "logger.info('[accountSync] initializing');",
      "logger.info('[accountSync] initialized');",
      "logger.info('[accountSync] invoked');",
      `logger.info('[accountSync] request', {
      action: initialized.isKnownAction(requestedAction) ? requestedAction : 'invalid',
    });`,
      `logger.error('[accountSync] unhandled', {
      name: error instanceof Error ? error.name : 'UnknownError',
      code: error && typeof error === 'object' && 'code' in error ? String(error.code) : undefined,
    });`,
    ]);
  });
});
