// Preserved unpublished content; excluded from the miniapp runtime package.
import type { PracticalSkill } from '../miniprogram/data/practical-skills';

export const UNPUBLISHED_INSPECTOR_PRACTICAL_SKILLS: PracticalSkill[] = [
  {
    id: 'sampling',
    occupation: '4-08-05-01',
    title: '粮油扦样',
    summary: '先界定批次，再按适用标准布点取样，保证样品具有代表性和可追溯性。',
    iconAsset: '/assets/practical/sampler.png',
    purpose: '取得具有代表性且全程可追溯的粮油样品。',
    preparations: [
      '确认适用的现行扦样方法',
      '核对批次、数量和状态',
      '准备洁净适用的器具、容器和标签',
    ],
    steps: [
      { title: '识别批次', detail: '核对品种、批号、货位和边界，发现混批或状态不明时先报告。' },
      {
        title: '按法布点',
        detail: '严格依适用现行标准和受控作业文件确定点位与份数，不凭经验随意减少。',
      },
      { title: '规范取样', detail: '使用洁净器具依次取样，防止遗漏、污染和样品损失。' },
      { title: '混合标识', detail: '按规定形成原始样品，立即标注批次、地点、时间和人员信息。' },
    ],
    safetyNotes: ['车、船、粮堆或高处扦样必须先落实现场安全措施，不在移动设备或无防护条件下操作。'],
    commonMistakes: ['先取样后补写批次标签', '只取方便到达的位置，造成代表性不足'],
    relatedQuestionIds: ['QI-L5-000001', 'QI-L5-000002'],
    sourceIds: ['SRC-0002', 'SRC-0006', 'SRC-0010'],
    standardReference:
      'GB/T 5491-2025《粮食、油料检验 扦样、分样法》；政府储备粮油质量检查扦样检验管理办法',
  },
  {
    id: 'sample-division',
    occupation: '4-08-05-01',
    title: '样品混合与分样',
    summary: '在避免损失和偏析的前提下，将原始样品制成满足检验与留样要求的样品。',
    iconAsset: '/assets/practical/sampler.png',
    purpose: '形成均匀、身份清楚且满足检验和留样要求的分样。',
    preparations: ['确认样品身份和包装完整', '准备洁净干燥的分样器具', '核对检验、复检和留样需求'],
    steps: [
      { title: '检查样品', detail: '核对标签、数量、状态和交接信息，异常先记录并确认。' },
      { title: '充分混合', detail: '依适用方法使样品均匀，避免粗细、轻重组分在操作中偏析。' },
      { title: '规范缩分', detail: '按现行标准选择适用分样方法，重复操作至满足后续用途。' },
      { title: '分别封装', detail: '检验样、复检样和留样分别装入适宜容器并完成唯一标识。' },
    ],
    safetyNotes: ['操作产生粉尘时按实验室要求采取通风和个人防护，器具使用后及时清洁。'],
    commonMistakes: ['直接从未混匀样品表层抓取检验样', '缩分后标签未同步，导致样品身份混淆'],
    relatedQuestionIds: ['QI-L4-000006', 'QI-L5-000002'],
    sourceIds: ['SRC-0002', 'SRC-0010', 'SRC-0011'],
    standardReference:
      'GB/T 5491-2025《粮食、油料检验 扦样、分样法》；GB/T 5490-2010《粮油检验 一般规则》',
  },
  {
    id: 'moisture-test',
    occupation: '4-08-05-01',
    title: '水分检验作业要点',
    summary: '围绕方法确认、样品制备、仪器状态、平行测定和原始记录控制检验质量。',
    iconAsset: '/assets/practical/moisture-test.png',
    purpose: '准确测定样品水分并保留可复核的质量控制记录。',
    preparations: [
      '确认粮种对应的现行检验方法',
      '核对样品身份和状态',
      '检查仪器校准或核查状态及环境条件',
    ],
    steps: [
      { title: '选择方法', detail: '按样品类型、检验目的和受控文件确认适用方法及关键条件。' },
      { title: '制备样品', detail: '依方法要求完成混匀、缩分和必要制备，减少水分变化。' },
      {
        title: '实施测定',
        detail: '严格按现行标准与仪器作业文件操作，不自行更改时间、温度或计算规则。',
      },
      {
        title: '复核记录',
        detail: '记录原始读数、平行结果、仪器和环境信息，按规则判断是否需要复测。',
      },
    ],
    safetyNotes: ['涉及加热、研磨或电气设备时执行防烫、防尘和断电清洁要求。'],
    commonMistakes: ['样品敞口放置过久', '只抄最终结果，未保留称量或仪器原始数据'],
    relatedQuestionIds: ['QI-L4-000001', 'QI-L3-000008'],
    sourceIds: ['SRC-0002', 'SRC-0011'],
    standardReference: 'GB/T 5490-2010《粮油检验 一般规则》及样品对应的现行水分检验方法标准',
    nonCurrentSourceIds: ['SRC-0003'],
    nonCurrentReference: '现行粮油行业标准目录（仅作书目定位，不支撑具体步骤、参数或限值）',
  },
  {
    id: 'impurity-test',
    occupation: '4-08-05-01',
    title: '杂质检验作业要点',
    summary: '按适用标准完成样品称取、筛理与分类，避免组分遗漏和主观边界漂移。',
    iconAsset: '/assets/practical/sampler.png',
    purpose: '准确分离和量化杂质组分，保证结果一致、可追溯。',
    preparations: [
      '确认粮种对应的杂质检验方法',
      '准备适用且状态正常的筛具和衡器',
      '检查样品与容器标识',
    ],
    steps: [
      {
        title: '核对方法',
        detail: '确认检验对象、分类边界、所需试样量和结果表达均来自当前受控方法。',
      },
      { title: '混匀称取', detail: '从代表性样品中按方法取得试样，保留原始称量记录。' },
      { title: '筛理分拣', detail: '依标准顺序操作，分类存放各组分，防止散失、重复或交叉混入。' },
      { title: '计算复核', detail: '核对各组分质量、计算过程和允许差，异常时按质量控制程序处理。' },
    ],
    safetyNotes: ['筛理和清扫时控制粉尘，不用手直接清理仍在运行的设备。'],
    commonMistakes: ['分类容器无标识导致组分混淆', '筛上、筛下物散失后仍继续计算'],
    relatedQuestionIds: ['QI-L3-000002', 'QI-L4-000001'],
    sourceIds: ['SRC-0002', 'SRC-0011'],
    standardReference: 'GB/T 5490-2010《粮油检验 一般规则》及样品对应的现行杂质检验方法标准',
    nonCurrentSourceIds: ['SRC-0003'],
    nonCurrentReference: '现行粮油行业标准目录（仅作书目定位，不支撑具体步骤、参数或限值）',
  },
  {
    id: 'test-weight',
    occupation: '4-08-05-01',
    title: '容重测定作业要点',
    summary: '确认适用范围和仪器状态，按规定装样、读数并完成平行结果复核。',
    iconAsset: '/assets/practical/sampler.png',
    purpose: '在受控操作条件下获得稳定、可复核的容重结果。',
    preparations: [
      '确认粮种和现行容重测定方法',
      '检查容重器、衡器及配套部件状态',
      '将样品混匀并核对标识',
    ],
    steps: [
      { title: '装配核查', detail: '依仪器作业文件检查各部件完整、洁净、放置稳定。' },
      { title: '规范装样', detail: '按适用标准完成样品处理和装填，保持每次操作方式一致。' },
      { title: '称量读数', detail: '待状态稳定后读取并记录，不以估读值替代原始示值。' },
      { title: '平行复核', detail: '比较平行结果和质量控制要求，超出条件时查找原因并按程序重做。' },
    ],
    safetyNotes: ['搬放金属部件时防夹手、防跌落；清理前确认设备处于安全状态。'],
    commonMistakes: ['装样速度和方式前后不一致', '仪器未置稳或部件有残留样品就开始测定'],
    relatedQuestionIds: ['QI-L5-000003', 'QI-L4-000003'],
    sourceIds: ['SRC-0002', 'SRC-0011'],
    standardReference: 'GB/T 5490-2010《粮油检验 一般规则》及粮种对应的现行容重测定方法标准',
    nonCurrentSourceIds: ['SRC-0003'],
    nonCurrentReference: '现行粮油行业标准目录（仅作书目定位，不支撑具体步骤、参数或限值）',
  },
  {
    id: 'laboratory-safety',
    occupation: '4-08-05-01',
    title: '检验室安全与记录',
    summary: '从人员、样品、试剂、设备和数据五个方面完成开工前检查与收尾。',
    iconAsset: '/assets/practical/moisture-test.png',
    purpose: '保障检验人员、样品、设备和原始数据全过程安全可控。',
    preparations: [
      '了解当日检验任务和风险',
      '核对个人防护与应急设施',
      '确认受控方法和记录表单版本',
    ],
    steps: [
      { title: '开工检查', detail: '检查通风、电源、消防、洗眼等条件及设备状态，异常先停用报告。' },
      {
        title: '分区操作',
        detail: '样品、试剂和废弃物按实验室规则标识与放置，避免交叉污染和误用。',
      },
      { title: '同步记录', detail: '操作同时记录原始数据、异常和处置，不凭记忆事后集中补写。' },
      { title: '结束复位', detail: '关闭设备和能源，清洁台面，处置废弃物并完成样品与记录交接。' },
    ],
    safetyNotes: [
      '不使用无标签试剂，不独自处理未知泄漏；发生人身风险时优先撤离、求助并启动应急程序。',
    ],
    commonMistakes: ['用非受控纸张记录后再誊抄', '样品、试剂或废弃物容器缺少身份和状态标识'],
    relatedQuestionIds: ['QI-L4-000002', 'QI-L5-000004', 'QI-L5-000007'],
    sourceIds: ['SRC-0002', 'SRC-0005', 'SRC-0011'],
    standardReference:
      '农产品食品检验员国家职业技能标准（2019年版）；GB/T 5490-2010《粮油检验 一般规则》',
  },
];
